name: Java Lint
on:
  pull_request:
    paths:
      - "java/**"
      - "codegen/lib-openapi.json"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "codegen/lib-openapi.json"

jobs:
  dotnet:
    name: Java Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build
        run: |
          cd java
          ./gradlew build
